StartupEvents.registry('item', event => {
    event.create('incomplete_black_hole_1').displayName('Micro Black Hole')
    event.create('incomplete_black_hole_2').displayName('Macro Black Hole')
    event.create('incomplete_black_hole_3').displayName('Tiny Black Hole')
    event.create('incomplete_black_hole_4').displayName('Small Black Hole')
    event.create('incomplete_black_hole_5').displayName('Medium Black Hole')
    event.create('incomplete_black_hole_6').displayName('Large Black Hole')
    event.create('incomplete_black_hole_7').displayName('Huge Black Hole')
    event.create('incomplete_black_hole_8').displayName('Massive Black Hole')
    event.create('completed_black_hole').displayName('Gigantic Black Hole').glow(true)
    event.create('prepared_incomplete_black_hole_1').displayName('Prepared Micro Black Hole')
    event.create('prepared_incomplete_black_hole_2').displayName('Prepared Macro Black Hole')
    event.create('prepared_incomplete_black_hole_3').displayName('Prepared Tiny Black Hole')
    event.create('prepared_incomplete_black_hole_4').displayName('Prepared Small Black Hole')
    event.create('prepared_incomplete_black_hole_5').displayName('Prepared Medium Black Hole')
    event.create('prepared_incomplete_black_hole_6').displayName('Prepared Large Black Hole')
    event.create('prepared_incomplete_black_hole_7').displayName('Prepared Huge Black Hole')
    event.create('prepared_incomplete_black_hole_8').displayName('Prepared Massive Black Hole')
    event.create('invisible_item').displayName('Invisible Item').tooltip('§3Nothing to see here!§r')
})